[features]
seeds = false
skip-lint = false

[programs.localnet]
energy_injection = "DrReEY58u59wdn223dBCfNMNXGbNcuWzS9o81WEAwnmA"
energy_bidding = "H4EeWD6PBphuaJZW4U9FVMdNhZtdEcJU7zt7umMYzYNg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
