[features]
seeds = false
skip-lint = false

[programs.localnet]
energy_injection = "8HAvCmA3sB8f5agvZmBXDepLmEToB8YwnZgt9kcitzbr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
