[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toe = "DCFHJduxcaG6By7sy4M9kMnTuaUCMkgR6MgmX2cosyvi"
energy_injection = "DrReEY58u59wdn223dBCfNMNXGbNcuWzS9o81WEAwnmA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
