[features]
seeds = false
skip-lint = false

[programs.localnet]
energy_market = "FT6mST1GsDeRTDfu7gHJpJPdNMNMGy8KJY6kASf6ARo3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
